/*
 * generated by Xtext
 */
package org.jbehave.ide.eclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JBehaveStoryUiModule extends org.jbehave.ide.eclipse.ui.AbstractJBehaveStoryUiModule {
	public JBehaveStoryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
