/*
 * generated by Xtext
 */
package org.jbehave.ide.eclipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JBehaveStoryRuntimeModule extends org.jbehave.ide.eclipse.AbstractJBehaveStoryRuntimeModule {

}
