/*
* generated by Xtext
*/
package org.jbehave.ide.eclipse.ui.contentassist;

import org.jbehave.ide.eclipse.ui.contentassist.AbstractJBehaveStoryProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JBehaveStoryProposalProvider extends AbstractJBehaveStoryProposalProvider {

}
