Narrative: Simple demonstration of jbehave.
In order to test my game
As a gamer
I want to run those test.

Given a 5 by 5 game
When I toggle the cell at (2, 3)
Then the grid should look like
.....
.....
.....
..X..
.....
When I toggle the cell at (2, 4)
Then the grid should look like
.....
.....
.....
..X..
..X..
When I toggle the cell at (2, 3)
Then the grid should look like
.....
.....
.....
.....
..X..
When I erase the grid
Then the grid should be
.....
.....
.....
.....
.....